### ISSUE TITLE
Interrupteur ne s'activant pas.

### ISSUE THREAD

**Issue by LeagueMaker95** [LeagueMaker95/Near-X-one#3]
Hello, Makers,
Here's my problem:

 During an action, an event occurs in the game, so far, everything is fine.
Then I activate a switch but this one doesn't activate and so the next event doesn't happen. 
Is it because of the switches?
Could you help me?

**Comment by adaptivui** [comment]
Hello @LeagueMaker95,

I'm not very expermiented on switchs but you could test it in another environment (empty map for instance) to check if it is the source of the issue. I'm pretty sure it's a typo.

If it still doesn't work, I suggest you to give more information on your switch implementation so that other can help you more efficiently.

Good luck

**Comment by LeagueMaker95** [comment]
Merci collaborateur et j'ai corrigé ce bug mais je ne toujours pas compris
 le bug?
